### ISSUE TITLE
Uncaught TypeError: Cannot read property 'offsetWidth' of undefined

### ISSUE THREAD

**Issue by hnaeem96** [hnaeem96/newyorkcity#2]
at c.slide (https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js:6:6975)
    at c.next (https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js:6:6216)
    at e (https://code.jquery.com/jquery-3.1.1.min.js:2:3655)

Sometimes while getting news requests with angular, the carousel does not get filled with the data causing this error to occur with the carousel feature. Maybe try loading all info including images before allowing html to use it?

**Comment by hnaeem96** [comment]
Solved, seemed to have been an issue with the way I was retrieving my news data. Despite the fix, I will be moving to a new news API source.
